FE#37 Add login API
Bartek-Figat/tsx-react pull request #38
Opened 2022-09-14 13:19 UTC by namelessolo

2022-09-15 11:46 UTC, Bartek-Figat commented
Looks good.

2022-09-16 15:47 UTC, masterHAWK99 requested changes

2022-09-16 15:47 UTC, masterHAWK99 commented on packages/frontEnd/src/services/AuthService.ts
> +  name: string;
Please use Intersection Types

2022-09-16 15:47 UTC, masterHAWK99 commented on packages/frontEnd/src/slice/login.tsx
> +}
Add variable for checking if user is logged

2022-09-20 12:47 UTC, merged